name: daytona550
favicon: null
layout_spectrum: 0.00812
typography_spectrum: 0.50993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ac132c'
    - '#071c60'
    - '#e2adb6'
    - '#c76272'
  brandStrength: 0.7358420020900667
  lightness: 0.25275600305758417
  saturation: 0.223317657597363
  rhythmicContrast: 0.3917225517798215
purpose: []
